// SyncBridge Mock Data — from 08_MOCK_DATA.md

export const MOCK_USERS = [
  {
    id: 'user_001',
    fullName: 'Sarah Johnson',
    email: 'sarah@acmehvac.com',
    role: 'admin',
    organisationId: 'org_001',
    avatarInitials: 'SJ',
  },
  {
    id: 'user_002',
    fullName: 'Mike Chen',
    email: 'mike@acmehvac.com',
    role: 'editor',
    organisationId: 'org_001',
    avatarInitials: 'MC',
  },
  {
    id: 'user_super',
    fullName: 'Alex Rivera',
    email: 'alex@syncbridge.io',
    role: 'super_admin',
    organisationId: 'org_syncbridge',
    avatarInitials: 'AR',
  },
  {
    id: 'user_003',
    fullName: 'Priya Patel',
    email: 'priya@acmehvac.com',
    role: 'organisation_admin',
    organisationId: 'org_001',
    avatarInitials: 'PP',
  },
];

export const MOCK_ORGS = [
  {
    id: 'org_001',
    name: 'Acme HVAC',
    plan: 'pro',
    memberCount: 4,
    projectCount: 3,
    createdAt: '2025-01-10T09:00:00Z',
  },
  {
    id: 'org_002',
    name: 'Metro Plumbing Co',
    plan: 'free',
    memberCount: 2,
    projectCount: 1,
    createdAt: '2025-02-15T11:00:00Z',
  },
  {
    id: 'org_syncbridge',
    name: 'Synkazo Internal',
    plan: 'enterprise',
    memberCount: 5,
    projectCount: 10,
    createdAt: '2024-06-01T00:00:00Z',
  },
];

export const MOCK_PLATFORMS = [
  {
    id: 'servicetitan',
    name: 'ServiceTitan',
    color: '#FF6B2C',
    status: 'live',
    category: 'field_service',
  },
  {
    id: 'hubspot',
    name: 'HubSpot',
    color: '#FF7A59',
    status: 'live',
    category: 'crm',
  },
  {
    id: 'dataforma',
    name: 'Dataforma',
    color: '#0E76A8',
    status: 'live',
    category: 'roofing',
  },
  {
    id: 'texada',
    name: 'Texada',
    color: '#00ADEF',
    status: 'live',
    category: 'field_service',
  },
  {
    id: 'salesforce',
    name: 'Salesforce',
    color: '#00A1E0',
    status: 'coming_soon',
    category: 'crm',
  },
  {
    id: 'quickbooks',
    name: 'QuickBooks',
    color: '#2CA01C',
    status: 'coming_soon',
    category: 'accounting',
  },
  {
    id: 'zapier',
    name: 'Zapier',
    color: '#FF4A00',
    status: 'coming_soon',
    category: 'automation',
  },
];

export const MOCK_CONNECTIONS = [
  {
    id: 'conn_001',
    projectId: 'proj_001',
    platformId: 'servicetitan',
    type: 'source',
    status: 'connected',
    accountName: 'Acme HVAC — ServiceTitan',
    connectedAt: '2025-01-10T10:30:00Z',
    lastChecked: '2025-05-17T14:00:00Z',
  },
  {
    id: 'conn_002',
    projectId: 'proj_001',
    platformId: 'hubspot',
    type: 'destination',
    status: 'connected',
    accountName: 'Acme HVAC — HubSpot CRM',
    connectedAt: '2025-01-10T11:00:00Z',
    lastChecked: '2025-05-17T14:00:00Z',
  },
  {
    id: 'conn_003',
    projectId: 'proj_002',
    platformId: 'servicetitan',
    type: 'source',
    status: 'connected',
    accountName: 'Acme HVAC — ServiceTitan (Staging)',
    connectedAt: '2025-03-01T09:00:00Z',
    lastChecked: '2025-05-17T14:00:00Z',
  },
  {
    id: 'conn_004',
    projectId: 'proj_002',
    platformId: 'hubspot',
    type: 'destination',
    status: 'error',
    accountName: 'Acme HVAC — HubSpot (Sandbox)',
    connectedAt: '2025-03-01T09:30:00Z',
    lastChecked: '2025-05-17T14:00:00Z',
  },
  {
    id: 'conn_005',
    projectId: 'proj_003',
    platformId: 'servicetitan',
    type: 'source',
    status: 'connected',
    accountName: 'Acme HVAC — ServiceTitan',
    connectedAt: '2025-04-20T08:00:00Z',
    lastChecked: '2025-05-17T14:00:00Z',
  },
  {
    id: 'conn_006',
    projectId: 'proj_003',
    platformId: 'hubspot',
    type: 'destination',
    status: 'connected',
    accountName: 'Acme HVAC — HubSpot CRM',
    connectedAt: '2025-04-20T08:30:00Z',
    lastChecked: '2025-05-17T14:00:00Z',
  },
];

export const MOCK_PROJECTS = [
  {
    id: 'proj_001',
    organisationId: 'org_001',
    name: 'Main ServiceTitan ↔ HubSpot Sync',
    description: 'Primary production sync for Acme HVAC',
    sourcePlatformId: 'servicetitan',
    destPlatformId: 'hubspot',
    status: 'active',
    totalRecordsSynced: 14200,
    totalErrorCount: 3,
    jobCount: 3,
    lastSyncedAt: '2025-05-17T14:30:00Z',
    createdAt: '2025-01-10T10:00:00Z',
  },
  {
    id: 'proj_002',
    organisationId: 'org_001',
    name: 'Staging Environment Test',
    description: 'Testing new field mappings before production',
    sourcePlatformId: 'servicetitan',
    destPlatformId: 'hubspot',
    status: 'error',
    totalRecordsSynced: 980,
    totalErrorCount: 47,
    jobCount: 1,
    lastSyncedAt: '2025-05-16T09:15:00Z',
    createdAt: '2025-03-01T09:00:00Z',
  },
  {
    id: 'proj_003',
    organisationId: 'org_001',
    name: 'Invoices & Deals Sync',
    description: 'Sync invoices from ServiceTitan to HubSpot deals',
    sourcePlatformId: 'servicetitan',
    destPlatformId: 'hubspot',
    status: 'draft',
    totalRecordsSynced: 0,
    totalErrorCount: 0,
    jobCount: 0,
    lastSyncedAt: null,
    createdAt: '2025-04-20T08:00:00Z',
  },
];

export const MOCK_JOBS = [
  {
    id: 'job_001',
    projectId: 'proj_001',
    name: 'Customers → Contacts',
    sourceObject: 'customers',
    destObject: 'contacts',
    direction: 'one_way',
    status: 'active',
    scheduleType: 'interval',
    intervalMinutes: 15,
    recordsSynced: 8500,
    errorCount: 1,
    lastRunAt: '2025-05-17T14:15:00Z',
    nextRunAt: '2025-05-17T14:30:00Z',
    createdAt: '2025-01-10T12:00:00Z',
  },
  {
    id: 'job_002',
    projectId: 'proj_001',
    name: 'Jobs → Deals',
    sourceObject: 'jobs',
    destObject: 'deals',
    direction: 'one_way',
    status: 'active',
    scheduleType: 'interval',
    intervalMinutes: 30,
    recordsSynced: 4200,
    errorCount: 2,
    lastRunAt: '2025-05-17T14:00:00Z',
    nextRunAt: '2025-05-17T14:30:00Z',
    createdAt: '2025-01-10T12:30:00Z',
  },
  {
    id: 'job_003',
    projectId: 'proj_001',
    name: 'Invoices → Deals (Financial)',
    sourceObject: 'invoices',
    destObject: 'deals',
    direction: 'one_way',
    status: 'paused',
    scheduleType: 'cron',
    cronExpression: '0 9 * * 1-5',
    recordsSynced: 1500,
    errorCount: 0,
    lastRunAt: '2025-05-16T09:00:00Z',
    nextRunAt: null,
    createdAt: '2025-02-01T10:00:00Z',
  },
  {
    id: 'job_004',
    projectId: 'proj_002',
    name: 'Customers → Contacts (Staging)',
    sourceObject: 'customers',
    destObject: 'contacts',
    direction: 'one_way',
    status: 'error',
    scheduleType: 'interval',
    intervalMinutes: 60,
    recordsSynced: 980,
    errorCount: 47,
    lastRunAt: '2025-05-16T09:15:00Z',
    nextRunAt: '2025-05-17T15:00:00Z',
    createdAt: '2025-03-01T10:00:00Z',
  },
];

export const MOCK_FIELD_MAPPINGS = {
  job_001: [
    {
      id: 'fm_001',
      sourceField: { key: 'id', label: 'Customer ID', type: 'string' },
      destField: { key: 'hs_object_id', label: 'HubSpot ID', type: 'string' },
      transformType: 'direct',
      required: true,
    },
    {
      id: 'fm_002',
      sourceField: { key: 'name', label: 'Full Name', type: 'string' },
      destField: null,
      isBridge: true,
      bridgeTargets: [
        { key: 'firstname', label: 'First Name', type: 'string' },
        { key: 'lastname', label: 'Last Name', type: 'string' },
      ],
      transformType: 'split_name',
      required: true,
    },
    {
      id: 'fm_003',
      sourceField: { key: 'email', label: 'Email', type: 'string' },
      destField: { key: 'email', label: 'Email', type: 'string' },
      transformType: 'direct',
      required: true,
    },
    {
      id: 'fm_004',
      sourceField: { key: 'phone', label: 'Phone Number', type: 'string' },
      destField: { key: 'phone', label: 'Phone', type: 'string' },
      transformType: 'direct',
      required: false,
    },
    {
      id: 'fm_005',
      sourceField: { key: 'address', label: 'Street Address', type: 'string' },
      destField: { key: 'address', label: 'Address', type: 'string' },
      transformType: 'direct',
      required: false,
    },
    {
      id: 'fm_006',
      sourceField: { key: 'city', label: 'City', type: 'string' },
      destField: { key: 'city', label: 'City', type: 'string' },
      transformType: 'direct',
      required: false,
    },
    {
      id: 'fm_007',
      sourceField: { key: 'type', label: 'Customer Type', type: 'enum' },
      destField: {
        key: 'customer_type',
        label: 'Customer Type',
        type: 'string',
      },
      transformType: 'enum_map',
      required: false,
    },
    {
      id: 'fm_008',
      sourceField: {
        key: 'createdOn',
        label: 'Created Date',
        type: 'datetime',
      },
      destField: { key: 'createdate', label: 'Create Date', type: 'datetime' },
      transformType: 'direct',
      required: false,
    },
  ],
};

export const MOCK_SOURCE_FIELDS = {
  customers: [
    { key: 'id', label: 'Customer ID', type: 'string', required: true },
    { key: 'name', label: 'Full Name', type: 'string', required: true },
    { key: 'email', label: 'Email', type: 'string', required: false },
    { key: 'phone', label: 'Phone Number', type: 'string', required: false },
    {
      key: 'address',
      label: 'Street Address',
      type: 'string',
      required: false,
    },
    { key: 'city', label: 'City', type: 'string', required: false },
    { key: 'state', label: 'State', type: 'string', required: false },
    { key: 'zip', label: 'ZIP Code', type: 'string', required: false },
    { key: 'type', label: 'Customer Type', type: 'enum', required: false },
    {
      key: 'balance',
      label: 'Account Balance',
      type: 'number',
      required: false,
    },
    {
      key: 'createdOn',
      label: 'Created Date',
      type: 'datetime',
      required: false,
    },
    {
      key: 'modifiedOn',
      label: 'Modified Date',
      type: 'datetime',
      required: false,
    },
    { key: 'active', label: 'Is Active', type: 'boolean', required: false },
  ],
  jobs: [
    { key: 'id', label: 'Job ID', type: 'string', required: true },
    { key: 'customerId', label: 'Customer ID', type: 'string', required: true },
    { key: 'status', label: 'Job Status', type: 'enum', required: true },
    { key: 'type', label: 'Job Type', type: 'string', required: false },
    { key: 'total', label: 'Job Total', type: 'number', required: false },
    {
      key: 'completedOn',
      label: 'Completion Date',
      type: 'datetime',
      required: false,
    },
    {
      key: 'technicianId',
      label: 'Technician ID',
      type: 'string',
      required: false,
    },
    { key: 'notes', label: 'Notes', type: 'string', required: false },
  ],
  invoices: [
    { key: 'id', label: 'Invoice ID', type: 'string', required: true },
    { key: 'jobId', label: 'Job ID', type: 'string', required: true },
    { key: 'total', label: 'Invoice Total', type: 'number', required: true },
    { key: 'dueDate', label: 'Due Date', type: 'date', required: false },
    { key: 'paidOn', label: 'Paid Date', type: 'date', required: false },
    { key: 'status', label: 'Invoice Status', type: 'enum', required: false },
  ],
};

export const MOCK_DEST_FIELDS = {
  contacts: [
    {
      key: 'hs_object_id',
      label: 'HubSpot ID',
      type: 'string',
      required: false,
    },
    { key: 'firstname', label: 'First Name', type: 'string', required: false },
    { key: 'lastname', label: 'Last Name', type: 'string', required: false },
    { key: 'email', label: 'Email', type: 'string', required: true },
    { key: 'phone', label: 'Phone', type: 'string', required: false },
    { key: 'address', label: 'Address', type: 'string', required: false },
    { key: 'city', label: 'City', type: 'string', required: false },
    { key: 'state', label: 'State/Region', type: 'string', required: false },
    { key: 'zip', label: 'Postal Code', type: 'string', required: false },
    {
      key: 'customer_type',
      label: 'Customer Type',
      type: 'string',
      required: false,
    },
    {
      key: 'createdate',
      label: 'Create Date',
      type: 'datetime',
      required: false,
    },
    {
      key: 'lastmodifieddate',
      label: 'Last Modified',
      type: 'datetime',
      required: false,
    },
  ],
  deals: [
    { key: 'hs_object_id', label: 'Deal ID', type: 'string', required: false },
    { key: 'dealname', label: 'Deal Name', type: 'string', required: true },
    { key: 'amount', label: 'Amount', type: 'number', required: false },
    { key: 'dealstage', label: 'Deal Stage', type: 'enum', required: false },
    { key: 'closedate', label: 'Close Date', type: 'date', required: false },
    { key: 'pipeline', label: 'Pipeline', type: 'string', required: false },
    {
      key: 'hubspot_owner_id',
      label: 'Owner',
      type: 'string',
      required: false,
    },
  ],
};

export const MOCK_SYNC_RUNS = [
  {
    id: 'run_001',
    jobId: 'job_001',
    status: 'success',
    recordsProcessed: 42,
    recordsFailed: 0,
    startedAt: '2025-05-17T14:15:00Z',
    finishedAt: '2025-05-17T14:15:45Z',
    durationMs: 45000,
  },
  {
    id: 'run_002',
    jobId: 'job_001',
    status: 'success',
    recordsProcessed: 38,
    recordsFailed: 0,
    startedAt: '2025-05-17T14:00:00Z',
    finishedAt: '2025-05-17T14:00:40Z',
    durationMs: 40000,
  },
  {
    id: 'run_003',
    jobId: 'job_001',
    status: 'error',
    recordsProcessed: 50,
    recordsFailed: 1,
    startedAt: '2025-05-17T13:45:00Z',
    finishedAt: '2025-05-17T13:45:52Z',
    durationMs: 52000,
  },
  {
    id: 'run_004',
    jobId: 'job_002',
    status: 'success',
    recordsProcessed: 15,
    recordsFailed: 0,
    startedAt: '2025-05-17T14:00:00Z',
    finishedAt: '2025-05-17T14:00:30Z',
    durationMs: 30000,
  },
  {
    id: 'run_005',
    jobId: 'job_004',
    status: 'error',
    recordsProcessed: 100,
    recordsFailed: 47,
    startedAt: '2025-05-16T09:15:00Z',
    finishedAt: '2025-05-16T09:17:30Z',
    durationMs: 150000,
  },
];

export const MOCK_LOGS = [
  {
    id: 'log_001',
    level: 'error',
    message:
      "Failed to map field 'type' — enum value 'commercial_plus' not in destination schema",
    jobId: 'job_001',
    runId: 'run_003',
    timestamp: '2025-05-17T13:45:40Z',
  },
  {
    id: 'log_002',
    level: 'info',
    message: 'Sync run completed: 42 records processed, 0 errors',
    jobId: 'job_001',
    runId: 'run_001',
    timestamp: '2025-05-17T14:15:45Z',
  },
  {
    id: 'log_003',
    level: 'info',
    message: 'Sync run completed: 38 records processed, 0 errors',
    jobId: 'job_001',
    runId: 'run_002',
    timestamp: '2025-05-17T14:00:40Z',
  },
  {
    id: 'log_004',
    level: 'warn',
    message: 'Rate limit approaching: 850/1000 API calls used this hour',
    jobId: 'job_002',
    runId: 'run_004',
    timestamp: '2025-05-17T14:00:28Z',
  },
  {
    id: 'log_005',
    level: 'error',
    message: 'HubSpot API returned 401 Unauthorized — token may be expired',
    jobId: 'job_004',
    runId: 'run_005',
    timestamp: '2025-05-16T09:16:00Z',
  },
  {
    id: 'log_006',
    level: 'error',
    message: "47 records failed: missing required field 'email'",
    jobId: 'job_004',
    runId: 'run_005',
    timestamp: '2025-05-16T09:17:00Z',
  },
  {
    id: 'log_007',
    level: 'info',
    message: 'Job paused by user sarah@acmehvac.com',
    jobId: 'job_003',
    runId: null,
    timestamp: '2025-05-16T08:00:00Z',
  },
];

export const MOCK_TEAM_MEMBERS = [
  {
    id: 'user_001',
    fullName: 'Sarah Johnson',
    email: 'sarah@acmehvac.com',
    role: 'admin',
    status: 'active',
    joinedAt: '2025-01-10T09:00:00Z',
    avatarInitials: 'SJ',
  },
  {
    id: 'user_002',
    fullName: 'Mike Chen',
    email: 'mike@acmehvac.com',
    role: 'editor',
    status: 'active',
    joinedAt: '2025-01-15T10:00:00Z',
    avatarInitials: 'MC',
  },
  {
    id: 'user_003',
    fullName: 'Priya Patel',
    email: 'priya@acmehvac.com',
    role: 'organisation_admin',
    status: 'active',
    joinedAt: '2025-02-01T09:00:00Z',
    avatarInitials: 'PP',
  },
  {
    id: 'user_004',
    fullName: 'James Wilson',
    email: 'james@acmehvac.com',
    role: 'editor',
    status: 'invited',
    joinedAt: '2025-05-10T14:00:00Z',
    avatarInitials: 'JW',
  },
];

// Current logged-in user (demo)
export const CURRENT_USER = MOCK_USERS[0]; // Sarah Johnson — admin
